export function getNetWorkConfig() {}
export function createNetWorkConfig() {}
export function updateNetWorkConfig() {}
export function deleteNetWorkConfig() {}
export function getNetWorkConfigType() {}
export function getRequestCreateNetWork() {}
export function getRequestCreateNetWorkType() {}
export function updateRequestCreateNetWork() {}
export function getNetWork() {}
export function getNetWorkStatistic() {}
